{
    "EMAIL":"naveen.p103@gmail.com",
    "PASS":"1234",
    "ADDRESS":"Bevoor, Channapatna",
    "DOB":"1990-11-22",
    "NAME":"Jay",
    "IS_VERIFIED":0
}
insert INTO PLACE (ID,NAME,STATE) values (1,'BANGLORE','KARNATAKA');
insert into PLACE(ID,NAME,STATE) VALUES(2,'MYSORE','KARNATAKA');
INSERT INTO PLACE(ID,NAME,STATE) VALUES(3,'MANGLORE','KARNATAKA');
INSERT INTO PLACE(ID,NAME,STATE) VALUES(4,'CHANNAPATNA','KARNATAKA');
INSERT INTO PLACE(ID,NAME,STATE) VALUES(5,'MANDYA','KARNATAKA');
INSERT INTO PLACE(ID,NAME,STATE) VALUES(6,'RAMANAGARA','KARNATAKA');
INSERT INTO PLACE(ID,NAME,STATE) VALUES(7,'MADDUR','KARNATAKA');
insert into USERS(NAME,EMAIL,PASS,DOB,PHONE_NUM,ADDRESS,IS_VERIFIED) VALUES ('JAY','NAVEENCHANDAN@GMAIL.COM','1234',2020-11-20,'991614100','BEVOORU','0');
insert into USERS(NAME,EMAIL,PASS,DOB,PHONE_NUM,ADDRESS,IS_VERIFIED) VALUES ('NAVEEN','CHANDAN@GMAIL.COM','4567',2019-11-20,'991664100','MYSORE','1');
insert into TRANSPORT_PRICE(TRANSPORT_TYPE,PRICE_PER_KM) VALUES("BUS",10);
insert into TRANSPORT_PRICE(TRANSPORT_TYPE,PRICE_PER_KM) VALUES("TRAIN",5);
