insert INTO travel.PLACE (ID,NAME,STATE) values (1,'BANGLORE','KARNATAKA');
insert into travel.PLACE(ID,NAME,STATE) VALUES(2,'MYSORE','KARNATAKA');
INSERT INTO travel.PLACE(ID,NAME,STATE) VALUES(3,'MANGLORE','KARNATAKA');
INSERT INTO travel.PLACE(ID,NAME,STATE) VALUES(4,'CHANNAPATNA','KARNATAKA');
INSERT INTO travel.PLACE(ID,NAME,STATE) VALUES(5,'MANDYA','KARNATAKA');
INSERT INTO travel.PLACE(ID,NAME,STATE) VALUES(6,'RAMANAGARA','KARNATAKA');
INSERT INTO travel.PLACE(ID,NAME,STATE) VALUES(7,'MADDUR','KARNATAKA');
commit;
insert into travel.TRANSPORT_PRICE(TRANSPORT_TYPE,PRICE_PER_KM) VALUES("BUS",10);
insert into travel.TRANSPORT_PRICE(TRANSPORT_TYPE,PRICE_PER_KM) VALUES("TRAIN",5);
commit;

INSERT INTO travel.ROUTES(ID,START_PLACE_ID,DEST_PLACE_ID,TRANSPORT_TYPE,DIST_KM) values (null,1,2,'BUS',150);
INSERT INTO travel.ROUTES(ID,START_PLACE_ID,DEST_PLACE_ID,TRANSPORT_TYPE,DIST_KM) values (null,1,2,'TRAIN',100);
commit;